[package]
name = "learn-by-questions"
version = "0.0.0"
edition = "2021"
author = "Yashasvi Sriram Patkuri <yash.3997@gmail.com>"

[dependencies]
pulldown-cmark = "0.9.1"
tera = "1.16.0"
glob = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
